org: dohyeon5626
app: licorice-functions
service: github-content-proxy

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: app.application
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - .env