org: dohyeon5626
app: licorice-functions
service: monitoring-system

provider:
  name: aws
  runtime: nodejs20.x

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: cron(10 0 * * ? *)
    timeout: 30
    memorySize: 1024

plugins:
  - serverless-dotenv-plugin

package:
  exclude:
    - .env