org: dohyeon5626
app: licorice-functions
service: monitoring-system

provider:
  name: aws
  runtime: nodejs20.x

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: cron(0 0 0 * ? *)